version: "3.9"
services:
  mysql:
    image: mysql:8.3.0
    environment:
      - MYSQL_DATABASE=e-commerce
      - MYSQL_ROOT_PASSWORD=12345
      - MYSQL_USER=root
    ports:
      - "3306:3306"
    volumes:
      - data-volume:/var/lib/mysql
    networks:
      - e-commerce-network
  redis:
    image: redis:7-alpine
    networks:
      - e-commerce-network
  api:
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    image: tranvinhhien1912/e-commerce:1.0.0
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=root:12345@tcp(mysql:3306)/e-commerce?parseTime=true
      - REDIS_ADDRESS=redis:6379
    depends_on:
      - mysql
      - redis
    networks:
      - e-commerce-network
    # entrypoint:
    #   [
    #     "/app/wait-for.sh",
    #     "postgres:5432",
    #     "--",
    #     "/app/start.sh"
    #   ]
    command: [ "/app/main" ]
volumes:
  data-volume:
networks:
  e-commerce-network:
    driver: bridge
