// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"
)

type Querier interface {
	CreateAccount(ctx context.Context, arg CreateAccountParams) error
	CreateCategory(ctx context.Context, arg CreateCategoryParams) error
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) error
	CreateDescriptionAttr(ctx context.Context, arg CreateDescriptionAttrParams) error
	CreateDiscount(ctx context.Context, arg CreateDiscountParams) error
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) error
	CreateOrder(ctx context.Context, arg CreateOrderParams) error
	CreateOrderDetail(ctx context.Context, arg CreateOrderDetailParams) error
	CreatePaymentMethod(ctx context.Context, arg CreatePaymentMethodParams) error
	CreateProductSKU(ctx context.Context, arg CreateProductSKUParams) error
	CreateProductSKUAttr(ctx context.Context, arg CreateProductSKUAttrParams) error
	CreateProductSPU(ctx context.Context, arg CreateProductSPUParams) error
	CreateRating(ctx context.Context, arg CreateRatingParams) error
	CreateRole(ctx context.Context, arg CreateRoleParams) error
	CreateRoleAccount(ctx context.Context, arg CreateRoleAccountParams) error
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) error
	DeleteAccount(ctx context.Context, accountID string) error
	DeleteCategory(ctx context.Context, categoryID string) error
	DeleteCustomer(ctx context.Context, customerID string) error
	DeleteCustomerAddress(ctx context.Context, idAddress string) error
	DeleteDescriptionAttr(ctx context.Context, descriptionAttrID string) error
	DeleteDiscount(ctx context.Context, discountID string) error
	DeleteEmployee(ctx context.Context, employeeID string) error
	DeleteOrder(ctx context.Context, orderID string) error
	DeleteOrderDetail(ctx context.Context, orderDetailID string) error
	DeletePaymentMethod(ctx context.Context, paymentMethodID string) error
	DeleteProductSKU(ctx context.Context, productSkuID string) error
	DeleteProductSKUAttr(ctx context.Context, productSkuAttrID string) error
	DeleteProductSPU(ctx context.Context, productsSpuID string) error
	DeleteRating(ctx context.Context, ratingID string) error
	DeleteRole(ctx context.Context, roleID string) error
	DeleteRoleAccount(ctx context.Context, roleAccountID string) error
	DeleteSupplier(ctx context.Context, supplierID string) error
	GetAccount(ctx context.Context, accountID string) (Accounts, error)
	GetAccountByUsername(ctx context.Context, username string) (Accounts, error)
	GetAccountRoles(ctx context.Context, accountID string) ([]Roles, error)
	GetCategory(ctx context.Context, categoryID string) (Categorys, error)
	GetCustomer(ctx context.Context, customerID string) (Customers, error)
	GetCustomerAddress(ctx context.Context, idAddress string) (CustomerAddress, error)
	GetCustomerByAccountID(ctx context.Context, accountID string) (Customers, error)
	GetDescriptionAttr(ctx context.Context, descriptionAttrID string) (DescriptionAttr, error)
	GetDiscount(ctx context.Context, discountID string) (Discounts, error)
	GetDiscountByCode(ctx context.Context, discountCode string) (Discounts, error)
	GetEmployee(ctx context.Context, employeeID string) (Employees, error)
	GetEmployeeByAccountID(ctx context.Context, accountID string) (Employees, error)
	GetOrder(ctx context.Context, orderID string) (Orders, error)
	GetOrderDetail(ctx context.Context, orderDetailID string) (OrderDetail, error)
	GetPaymentMethod(ctx context.Context, paymentMethodID string) (PaymentMethods, error)
	GetProductSKU(ctx context.Context, productSkuID string) (ProductSkus, error)
	GetProductSKUAttr(ctx context.Context, productSkuAttrID string) (ProductSkuAttrs, error)
	GetProductSPU(ctx context.Context, productsSpuID string) (ProductsSpu, error)
	GetRating(ctx context.Context, ratingID string) (Ratings, error)
	GetRole(ctx context.Context, roleID string) (Roles, error)
	GetRoleAccount(ctx context.Context, roleAccountID string) (RoleAccount, error)
	GetSupplier(ctx context.Context, supplierID string) (Suppliers, error)
	ListAccounts(ctx context.Context) ([]Accounts, error)
	ListAccountsPaged(ctx context.Context, arg ListAccountsPagedParams) ([]Accounts, error)
	ListActiveDiscounts(ctx context.Context) ([]Discounts, error)
	ListCategories(ctx context.Context) ([]Categorys, error)
	ListCategoriesPaged(ctx context.Context, arg ListCategoriesPagedParams) ([]Categorys, error)
	ListCustomerAddresses(ctx context.Context, customerID string) ([]CustomerAddress, error)
	ListCustomerAddressesPaged(ctx context.Context, arg ListCustomerAddressesPagedParams) ([]CustomerAddress, error)
	ListCustomerOrders(ctx context.Context, customerID string) ([]Orders, error)
	ListCustomers(ctx context.Context) ([]Customers, error)
	ListCustomersPaged(ctx context.Context, arg ListCustomersPagedParams) ([]Customers, error)
	ListDescriptionAttrs(ctx context.Context, productsSpuID string) ([]DescriptionAttr, error)
	ListDiscounts(ctx context.Context) ([]Discounts, error)
	ListDiscountsPaged(ctx context.Context, arg ListDiscountsPagedParams) ([]Discounts, error)
	ListEmployees(ctx context.Context) ([]Employees, error)
	ListEmployeesPaged(ctx context.Context, arg ListEmployeesPagedParams) ([]Employees, error)
	ListOrderDetails(ctx context.Context, orderID string) ([]OrderDetail, error)
	ListOrders(ctx context.Context) ([]Orders, error)
	ListOrdersPaged(ctx context.Context, arg ListOrdersPagedParams) ([]Orders, error)
	ListPaymentMethods(ctx context.Context) ([]PaymentMethods, error)
	ListPaymentMethodsPaged(ctx context.Context, arg ListPaymentMethodsPagedParams) ([]PaymentMethods, error)
	ListProductSKUAttrs(ctx context.Context, productsSpuID string) ([]ProductSkuAttrs, error)
	ListProductSKUs(ctx context.Context, productsSpuID string) ([]ProductSkus, error)
	ListProductSKUsPaged(ctx context.Context, arg ListProductSKUsPagedParams) ([]ProductSkus, error)
	ListProductSPUs(ctx context.Context) ([]ProductsSpu, error)
	ListProductSPUsByCategory(ctx context.Context, categoryID string) ([]ProductsSpu, error)
	ListProductSPUsPaged(ctx context.Context, arg ListProductSPUsPagedParams) ([]ProductsSpu, error)
	ListRatings(ctx context.Context, productsSpuID string) ([]Ratings, error)
	ListRatingsPaged(ctx context.Context, arg ListRatingsPagedParams) ([]Ratings, error)
	ListRoleAccounts(ctx context.Context) ([]RoleAccount, error)
	ListRoleAccountsPaged(ctx context.Context, arg ListRoleAccountsPagedParams) ([]RoleAccount, error)
	ListRoles(ctx context.Context) ([]Roles, error)
	ListRolesPaged(ctx context.Context, arg ListRolesPagedParams) ([]Roles, error)
	ListSuppliers(ctx context.Context) ([]Suppliers, error)
	ListSuppliersPaged(ctx context.Context, arg ListSuppliersPagedParams) ([]Suppliers, error)
	Login(ctx context.Context, username string) (LoginRow, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) error
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) error
	UpdateCustomerAddress(ctx context.Context, arg UpdateCustomerAddressParams) error
	UpdateDescriptionAttr(ctx context.Context, arg UpdateDescriptionAttrParams) error
	UpdateDiscount(ctx context.Context, arg UpdateDiscountParams) error
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) error
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) error
	UpdateOrderDetail(ctx context.Context, arg UpdateOrderDetailParams) error
	UpdatePaymentMethod(ctx context.Context, arg UpdatePaymentMethodParams) error
	UpdateProductSKU(ctx context.Context, arg UpdateProductSKUParams) error
	UpdateProductSKUAttr(ctx context.Context, arg UpdateProductSKUAttrParams) error
	UpdateProductSPU(ctx context.Context, arg UpdateProductSPUParams) error
	UpdateRating(ctx context.Context, arg UpdateRatingParams) error
	UpdateRole(ctx context.Context, arg UpdateRoleParams) error
	UpdateRoleAccount(ctx context.Context, arg UpdateRoleAccountParams) error
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) error
}

var _ Querier = (*Queries)(nil)
